name: KDRTracker
version: '${project.version}'
main: dansplugins.kdrtracker.KDRTracker
api-version: 1.13

commands:
  kdrtracker:
  kdrt:

permissions:
  kdrt.help:
    default: true
  kdrt.info:
    default: true